### ISSUE TITLE
Failed requirement 'boost/1.69.0@conan/stable' from 'MediaIPC-ue4/0.0.2@adamrehn/4.27'

### ISSUE THREAD

**Issue by blastodd** [adamrehn/ue4-conan-recipes#10]
https://github.com/adamrehn/ue4-conan-recipes/blob/00ff0cf764ab691b1843e6d5493d1a56f0d026d0/MediaIPC-ue4/0.0.2/conanfile.py#L14

While building full docker image this will error out.

https://github.com/adamrehn/ue4-docker/issues/201#issuecomment-917353094

The recipe might need to be updated with the new package name convention

**Comment by adamrehn** [comment]
Thanks for reporting this! I'd fixed this elsewhere, but evidently missed updating it here until now.
