### ISSUE TITLE
conflicting source directories detected for recipe

### ISSUE THREAD

**Issue by bmahlbrand** [adamrehn/ue4-conan-recipes#2]
When I run `ue4 conan build all` I'm met with the following output:

```
raise RuntimeError('conflicting source directories detected for recipe {}'.format(conflict)) from None
RuntimeError: conflicting source directories detected for recipe MediaIPC-ue4
```

I'm sure my previous attempts caused this, as I tried using this before having the UE4 source tree configured properly. My question is, where do I look for these conflicting directories? Is some sort of cache generated / broken package installations that I need to clean up?

**Comment by adamrehn** [comment]
This indicates that both the conan-ue4cli recipe cache and the current working directory contain recipes named `MediaIPC-ue4`. There are two options available:

- If you want to use the version from the current working directory then you can instruct conan-ue4cli to ignore the recipe cache by specifying the `--no-cache` flag.

- If you want to use the version from the recipe cache then you will need to run the command from a different directory. If you're using the recipe cache then it's often worthwhile running `ue4 conan update` first to ensure the cache contains the latest recipe scripts from this repository.

If you're running the build command from the root of this repository then the current working directory and the recipe cache will essentially be identical to one another, which means you should get identical results irrespective of which option you choose.

**Comment by bmahlbrand** [comment]
Thanks for clarifying.
